---
title: "CTT analysis for test: `math`"
date: "Generated `r date()`"
output: html_document
---

```{r echo = FALSE, message=FALSE}

library(QME)
library(dplyr)

data(math, math_key)

oz = odin_zeus(math, math_key) # NOTE: should include test name in data structure for reporting

```

```{r functions_def, echo = FALSE}

## All these functions take the output of odin_zeus as an input
item_names = function(x) {
  # Get the item names.  This should really be preserved & consistently applied in the 
  # item-level methods
  names(getRawTestNoID(x))
}  

basic_level_out = function(x) {
  ## Basic test info for first section
  x$test_level$descriptives[c("number_items", "number_examinees")]
} 

reliability_out = function(x) {
  ## Outputs for basic reliability
   
  rels = x$test_level$reliability
  
  ## This comes out clumsily as a list and should really be some 
  ## kind of table object in the original structure!
  ## Otherwise wouldn't need this code.
    
  rels2 = matrix(simplify2array(rels),
                 nrow = nrow(rels),
                 ncol = ncol(rels))
  attributes(rels2) = attributes (rels)  
  
  rels2
}

item_basics_out = function(x) {
  ## Outputs for BASIC item stats: deleted rel, discrimination, missing
  
  basics = x$item_level$item_stats[, c("difficulty", "corrected_pbis")]
  basics$deleted_alpha = x$item_level$del_alphas
  basics$Number_missing = x$item_level$missing$numMiss
  
  basics    
}



```

```{r basic_level, echo = FALSE}

basics = basic_level_out(oz)

```

**Number of items:** `r basics$number_items`, `XX` with missing data

**Number of examinees:** `r basics$number_examinees`, `XX` with missing data


## Reliability

```{r reliability, echo = FALSE, results = 'asis'}

myrels = reliability_out(oz)

knitr::kable(myrels, digits = 2)

```

*Brief notes about reliability assumptions here.*

## Item overview

```{r item_overview, echo = FALSE, results = 'asis'}

mybasics = item_basics_out(oz)

knitr::kable(mybasics, digits = 2)


```

